version: '3.7'

services:
  landau:
    image: docker.pkg.github.com/tobi6112/landau/landau:latest
    container_name: landau
    env_file:
      - ../../../.env
  landau-db:
    image: postgres:latest
    container_name: landau-db
    volumes:
      - landau-db-data:/var/lib/postgresql/data
    env_file:
      - ../../../.env
    ports:
      - 5432:5432

volumes:
  landau-db-data: