name: Set GH relase

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build jar
        run: |
          ./gradlew jar
          
      - name: Export version
        run: |
          echo "RELEASE_VERSION=(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/libs/Landau-${{ env.RELEASE_VERSION}}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
