name: Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Generate versions
      uses: HardNorth/github-version-generate@v1.1.1
      with:
        version-source: file
        version-file: gradle.properties
        version-file-extraction-pattern: '(?<=version=).+'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup git user
      uses: fregante/setup-git-user@v1

    - name: Export Image name
      run: |
        echo "IMAGE_NAME=docker.pkg.github.com/tobi6112/landau/landau:${{ env.RELEASE_VERSION }}" >> $GITHUB_ENV
    
    - name: setup pack
      uses: andrioid/setup-pack@v1.0.1
      with:
        pack-version: 0.18.1
    
    - name: Pack Build
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login -u tobi6112 --password-stdin 'https://docker.pkg.github.com'
        pack build ${{ env.IMAGE_NAME }} -v --builder paketobuildpacks/builder:base --buildpack gcr.io/paketo-buildpacks/gradle --publish

    - name: Release with Gradle
      id: release
      run: |
        ./gradlew release -Prelease.useAutomaticVersion=true \
        -Prelease.releaseVersion=${{ env.RELEASE_VERSION }} \
        -Prelease.newVersion=${{ env.NEXT_VERSION }}
